#!/bin/sh
CROSS_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$CROSS_DIR/bin/ld.lld
TARGET=x86_64-w64-mingw32
FLAGS="-m i386pep"
FLAGS="$FLAGS --pdb="

"$PROG" $FLAGS "$@" -O3 --gc-sections
