#!/bin/sh
CROSS_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$CROSS_DIR/bin/clang
FLAGS="$FLAGS -target x86_64-w64-mingw32 -march=x86-64 -mtune=generic"
FLAGS="$FLAGS  --sysroot $CROSS_DIR/x86_64-w64-mingw32"
FLAGS="$FLAGS -fuse-ld=x86_64-w64-mingw32-lld"
FLAGS="$FLAGS -gcodeview"

"$PROG" $FLAGS "$@" $CLANG_FLAGS
