#!/bin/bash
DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$DIR/bin/cross-ld.bfd
FLAGS="-O3"

if [ "$NO_CONFLTO" == "1" ]; then
    SKIP_OPT="-O0 --no-gc-sections"
fi

"$PROG" "$@" $FLAGS $BFD_FLAGS $SKIP_OPT
