#!/bin/bash
CROSS_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$CROSS_DIR/bin/clang++
FLAGS="$FLAGS -target x86_64-w64-mingw32 -march=x86-64 -mtune=generic"
FLAGS="$FLAGS --driver-mode=g++ -pthread --sysroot $CROSS_DIR/x86_64-w64-mingw32"
FLAGS="$FLAGS -fuse-ld=lld --ld-path=x86_64-w64-mingw32-ld"
FLAGS="$FLAGS -gcodeview"
FLAGS="$FLAGS -Wno-unused-command-line-argument"

if [ "$LTO" != "0" ] && [ "$CLANG_PACKAGES_LTO" == "ON" ]; then
    LTO_FLAGS="-flto=thin"
fi

if [ "$NO_CONFLTO" == "1" ]; then
    SKIP_OPT="-g0 -O0 -fno-lto -fno-data-sections -fno-function-sections"
fi

if [ "$GC" != "0" ]; then
    CLANG_GC="-fdata-sections -ffunction-sections"
fi

"$PROG" $LTO_FLAGS "$@" $FLAGS $CLANG_GC $CLANG_FLAGS $SKIP_OPT
