#!/bin/bash
DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$DIR/bin/ld.lld
TARGET=x86_64-w64-mingw32
POLICY="cache_size_bytes=1g:prune_interval=1m"
FLAGS="-m i386pep"
FLAGS="$FLAGS --thinlto-cache-dir=$PACKAGES_LTO_DIR --thinlto-cache-policy=$POLICY"

if [ "$NO_CONFLTO" == "1" ]; then
    SKIP_OPT="-O0 --lto-O0 --lto-CGO0 --no-gc-sections --no-guard-cf --build-id=none"
else
    FLAGS="$FLAGS -O3 --lto-O3 --lto-CGO3 -s -Xlink=-release -Xlink=-cetcompat"
    if [ "$GC" != "0" ]; then
        LLD_GC="--gc-sections --icf=safe"
    fi
    if [ "$PDB" == "1" ]; then
        FLAGS="$FLAGS --pdb="
    fi
    if [ "LLVM_ENABLE_PGO" == "GEN" ] || [ "LLVM_ENABLE_PGO" == "CSGEN" ]; then
        export LLVM_PROFILE_FILE="$LLVM_PROFILE_DATA_DIR/lld-%m.profraw" #enable profraw output only when NO_CONFLTO!=1
        export LLD_IN_TEST=1 #https://github.com/llvm/llvm-project/issues/52861
    fi
fi

"$PROG" "$@" $FLAGS $LLD_GC $LLD_FLAGS $SKIP_OPT