#!/bin/bash
DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$DIR/bin/clang
FLAGS="$FLAGS -target x86_64-w64-mingw32 -march=x86-64 -mtune=generic"
FLAGS="$FLAGS --sysroot $DIR/x86_64-w64-mingw32"
FLAGS="$FLAGS -fuse-ld=lld --ld-path=x86_64-w64-mingw32-ld"
FLAGS="$FLAGS -Wno-unused-command-line-argument"

if [ "$NO_CONFLTO" == "1" ]; then
    SKIP_OPT="-g0 -O0 -fno-lto -fno-data-sections -fno-function-sections"
else
    FLAGS="$FLAGS -gcodeview"
    if [ "$ENABLE_CCACHE" == "ON" ]; then
        CCACHE="ccache"
    fi
    if [ "$GC" != "0" ]; then
        CLANG_GC="-fdata-sections -ffunction-sections"
    fi
    CPU_COUNT=$(grep -c processor /proc/cpuinfo)
    if [ "$LTO" != "0" ] && [ "$CLANG_PACKAGES_LTO" == "ON" ]; then
        LTO_FLAGS="-flto=thin"
        if [ "$LLD_LTO_ALL_THREADS" == "1" ] && [ "$LTO_JOB" != "1" ]; then
            LTO_FLAGS="$LTO_FLAGS -flto-jobs=$CPU_COUNT"
        fi
    fi
    if [ "$LLVM_ENABLE_PGO" == "GEN" ] || [ "$LLVM_ENABLE_PGO" == "CSGEN" ]; then
        export LLVM_PROFILE_FILE="$LLVM_PROFILE_DATA_DIR/clang-%m.profraw" #enable profraw output only when NO_CONFLTO!=1
    fi    
fi

$CCACHE "$PROG" $LTO_FLAGS "$@" $FLAGS $CLANG_GC $CLANG_FLAGS $SKIP_OPT