#!/bin/bash
DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$DIR/bin/ld.lld
TARGET=x86_64-w64-mingw32
POLICY="cache_size_bytes=1g:prune_interval=1m"
FLAGS="-m i386pep"
FLAGS="$FLAGS --thinlto-cache-dir=/github/home/thinlto --thinlto-cache-policy=$POLICY"

if [ "$NO_CONFLTO" == "1" ]; then
    SKIP_OPT="-O0 --lto-O0 --lto-CGO0 --no-gc-sections --no-guard-cf --build-id=none"
else
    FLAGS="$FLAGS -O3 --lto-O3 --lto-CGO3 -s"
    if [ "$GC" != "0" ]; then
        LLD_GC="--gc-sections --icf=safe"
    fi
    if [ "$PDB" == "1" ]; then
        FLAGS="$FLAGS --pdb="
    fi
fi

"$PROG" "$@" $FLAGS $LLD_GC $LLD_FLAGS $SKIP_OPT
