#!/bin/bash
DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$DIR/bin/cross-gcc
FLAGS="$FLAGS -O3"

if [ "$NO_CONFLTO" == "1" ]; then
    SKIP_OPT="-g0 -O0 -fno-lto -fno-data-sections -fno-function-sections"
else
    if [ "$ENABLE_CCACHE" == "ON" ]; then
        CCACHE="ccache"
    fi
fi

if [ "@GCC_ARCH_HAS_AVX512@" == "ON" ]; then
    FLAGS="$FLAGS -Wa,-muse-unaligned-vector-move"
fi

$CCACHE "$PROG" "$@" $FLAGS $SKIP_OPT
