#!/bin/bash
DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$DIR/bin/clang++
FLAGS=""
FLAGS="$FLAGS -target x86_64-w64-mingw32"
FLAGS="$FLAGS -rtlib=compiler-rt -unwindlib=libunwind -stdlib=libc++"
FLAGS="$FLAGS --driver-mode=g++ -pthread"
FLAGS="$FLAGS --sysroot $DIR/x86_64-w64-mingw32"
FLAGS="$FLAGS -fuse-ld=lld --ld-path=x86_64-w64-mingw32-ld"
FLAGS="$FLAGS -gcodeview"
FLAGS="$FLAGS -Wno-unused-command-line-argument"

if [ "$GC" != "0" ]; then
    CLANG_GC="-fdata-sections -ffunction-sections"
fi

"$PROG" $FLAGS "$@" $CLANG_GC $CLANG_FLAGS
