#!/bin/bash
TARGET_ARCH="@target_arch@"

DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$DIR/bin/ld.lld
TARGET=${TARGET_ARCH}-w64-mingw32
FLAGS="-m i386pep"
FLAGS="$FLAGS -O3 --lto-O3 --lto-CGO3 -s -Xlink=-release"

if [ "$GC" != "0" ]; then
    LLD_GC="--gc-sections --icf=safe"
fi
if [ "$PDB" == "1" ]; then
    FLAGS="$FLAGS --pdb="
fi

"$PROG" $FLAGS "$@" $LLD_GC $LLD_FLAGS
