name: brotli
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  brotli:
    runs-on: ubuntu-latest
    steps:    
      - name: Install Dependencies
        run: |
          echo "deb http://cz.archive.ubuntu.com/ubuntu kinetic main universe" | sudo sh -c 'cat >> /etc/apt/sources.list'
          sudo apt-get -y update
          sudo apt-get -y install \
            pacman-package-manager \
            makepkg \
            yasm \
            nasm \
            cmake \
            ninja-build \
            pkgconf \
            python3-pip \
            unzip \
            p7zip-full \
            curl \
            wget
          pip3 install -U setuptools rst2pdf mako jsonschema meson
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
          
      - uses: actions/checkout@main
      - name: Setup Toolchain
        run: |
          curl -OL https://github.com/eko5624/toolchain-test/releases/download/toolchain/cross-gcc-mcf.7z
          7z x cross-gcc-mcf.7z
          rm cross-gcc-mcf.7z

      - name: Building
        run: |
          TOP_DIR=$(pwd)
          M_CROSS=$TOP_DIR/cross
          PATH="$M_CROSS/bin:$RUSTUP_LOCATION/.cargo/bin:$PATH"
          PKG_CONFIG_LIBDIR="$M_CROSS/opt/lib/pkgconfig"
          PKG_CONFIG="pkgconf --static"
          cd brotli-dev; makepkg
