name: brotli
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  brotli:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm docker
          sudo pacman -S --noconfirm --needed git gyp mercurial subversion ninja cmake ragel yasm nasm asciidoc enca gperf unzip p7zip xz clang python-pip python-cairo curl jq lib32-glib2 wget
          pip3 install -U --break-system-packages setuptools rst2pdf mako jsonschema meson
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD

      - name: Add builder user
        run: |
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Adding top_dir env
        run: |
           echo "top_dir=$(cd ~ && pwd)" >> $GITHUB_ENV
           
      - name: Checkout
        run: |
          cd ${{ env.top_dir }}
          git clone https://github.com/eko5624/toolchain-test
          
      - name: Setup Toolchain
        run: |
          cd ${{ env.top_dir }}
          curl -OL https://github.com/eko5624/toolchain-test/releases/download/toolchain/cross-gcc-mcf.7z
          7z x cross-gcc-mcf.7z && rm cross-gcc-mcf.7z
          
      - name: Building
        run: |
          export M_SOURCE=${{ env.top_dir }}/source
          export M_BUILD=${{ env.top_dir }}/build
          export M_CROSS=${{ env.top_dir }}/cross
          export PATH="$M_CROSS/bin:$RUSTUP_LOCATION/.cargo/bin:$PATH"
          export PKG_CONFIG_LIBDIR="$M_CROSS/opt/lib/pkgconfig"
          export PKG_CONFIG="pkgconf --static"
          
          MJOBS=$(grep -c processor /proc/cpuinfo)
          mkdir -p $M_SOURCE
          mkdir -p $M_BUILD
          
          cd $M_SOURCE
          git clone https://github.com/google/brotli.git
          cd $M_BUILD
          mkdir brotli-build
          cmake -G Ninja -H$M_SOURCE/brotli -B$M_BUILD/brotli-build \
            -DCMAKE_INSTALL_PREFIX=~/opt \
            -DCMAKE_TOOLCHAIN_FILE=~/toolchain-test/toolchain.cmake \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DBROTLI_EMSCRIPTEN=OFF
          ninja -j$MJOBS -C $M_BUILD/brotli-build
          
          sudo -H -u builder sudo chmod 775 -R ${{ env.top_dir }}
          cd ${{ env.top_dir }}/toolchain-test/brotli-dev
          sudo -H -u builder makepkg -sC --noconfirm
        
      - name: Release
        continue-on-error: true
        uses: softprops/action-gh-release@master
        with:
          tag_name: dev
          name: dev
          files: ${{ env.top_dir }}/toolchain-test/brotli-dev/*.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
