name: brotli
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  brotli:
    runs-on: ubuntu-latest
    steps:    
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/apt/sources.list
          sudo apt-get -y update
          sudo apt-get -y install \
            build-essential \
            yasm \
            nasm \
            git \
            cmake \
            gyp \
            checkinstall \
            bison \
            flex \
            gettext \
            mercurial \
            subversion \
            ninja-build \
            automake \
            pkgconf \
            libtool \
            libtool-bin \
            gcc-multilib \
            gperf \
            ragel \
            texinfo \
            autopoint \
            re2c \
            asciidoc \
            python3-pip \
            docbook2x \
            unzip \
            p7zip-full \
            curl \
            jq \
            wget
          brew install pacman makepkg
          pip3 install -U setuptools rst2pdf mako jsonschema meson
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
          
      - uses: actions/checkout@main
      - name: Setup Toolchain
        run: |
          curl -OL https://github.com/eko5624/toolchain-test/releases/download/toolchain/cross-gcc-mcf.7z
          7z x cross-gcc-mcf.7z
          rm cross-gcc-mcf.7z

      - name: Building
        run: |
          cd brotli-dev; makepkg
