name: Build target-llvm-mingw toolchain
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build_llvm:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - uses: actions/checkout@main      
      - name: Setup cross-llvm-mingw
        run: |
          curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-mingw-latest-ucrt-x86_64.7z
          7z x cross*.7z
          rm cross*.7z
      - name: Loading target-llvm cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: target-llvm-${{ github.run_id }}
          restore-keys: |
            target-llvm-
            
      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A target/bin)" ]]; then
            chmod +x ./target-llvm.sh
            ./target-llvm.sh
          fi

      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV  

      - name: Packaging toolchain
        run: 7z a target-llvm-latest.7z target/*

      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh target-llvm-latest.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh

      - name: Saving target-llvm cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: target-llvm-${{ github.run_id }}

  build_llvm-mingw:
    needs: build_llvm
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Run target-llvm-mingw.yml
        run: |
          curl -u eko5624:$GH_TOKEN \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/eko5624/toolchain/actions/workflows/target-llvm-mingw.yml/dispatches \
            -d '{"ref":"main"}'
