name: Build cross-llvm-mingw toolchain
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build_llvm:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - uses: actions/checkout@main
      - name: Loading llvm cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: cross-llvm-${{ github.run_id }}
          restore-keys: |
            cross-llvm-
            
      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A cross/bin)" ]]; then
            chmod +x ./cross-llvm.sh
            ./cross-llvm.sh
          fi

      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV  

      - name: Packaging toolchain
        run: 7z a cross-llvm-latest.7z cross/*

      - name: Saving llvm cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: cross-llvm-${{ github.run_id }}

      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh cross-llvm-latest.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh

  build_llvm-mingw:
    needs: build_llvm
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Run cross-llvm-mingw.yml
        run: |
          curl -u eko5624:$GH_TOKEN \
            -X POST -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/eko5624/toolchain/actions/workflows/cross-llvm-mingw.yml/dispatches \
            -d '{"ref":"main"}'