name: cross-llvm-clang-x86_64_v3
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      pgo:
        description: "Build toolchain with IR Profile Instrumentation"
        required: false
        default: "false"
        type: boolean
      llvm_thin_lto:
        description: "Build llvm with thin-lto"
        required: false
        default: "false"
        type: boolean
      llvm_full_lto:
        description: "Build llvm with full-lto"
        required: false
        default: "false"
        type: boolean
      llvm_ccache:
        description: "Build llvm with ccache"
        required: false
        default: "false"
        type: boolean
      package_lto:
        description: "Build packages with thin-lto"
        required: false
        default: "false"
        type: boolean        
      package_ccache:
        description: "Build packages with ccache"
        required: false
        default: "false"
        type: boolean
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Init variable
        run: |
          if [ ${{ inputs.pgo }} == 'true' ]; then
            echo "PGO=--enable-pgo_gen" >> $GITHUB_ENV
            echo "IR=-ir" >> $GITHUB_ENV
          else  
            unset PGO IR
          fi
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup llvm${{ env.IR }}
        run: |
          curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/llvm$IR-latest.7z
          7z x llvm*.7z
          rm llvm*.7z
          rm -rf cross/llvm-lto || true
          rm -rf cross/llvm-ccache || true            
      - name: Load llvm-project source
        uses: actions/cache@main
        id: llvm-source
        with:
          path: ${{ github.workspace }}/source/llvm-project
          key: llvm-source-cache
      - name: Build toolchain
        run: |
          set -x
          chmod +x ./cross-llvm-clang.sh
          ./cross-llvm-clang.sh --build-x86_64_v3 $PGO
      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV  
      - name: Package toolchain
        run: |
          7z a llvm-clang$IR-latest-ucrt-x86_64_v3.7z cross/*
          if [ ${{ inputs.pgo }} != 'true' ]; then
            cp llvm-clang$IR-latest-ucrt-x86_64_v3.7z llvm-clang$IR-${{ env.date }}-ucrt-x86_64_v3.7z
          fi
      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh llvm-clang$IR-latest-ucrt-x86_64_v3.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh