name: cross-llvm-mingw
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm --needed git ninja meson cmake yasm nasm zip unzip p7zip clang lld libc++ libc++abi python-pip curl jq wget
          pip3 install -U --break-system-packages setuptools rst2pdf mako jsonschema
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
          
      - uses: actions/checkout@main
      - name: Loading llvm cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: cross-llvm-${{ github.run_id }}
          restore-keys: |
            cross-llvm-
            
      - name: Building toolchain
        run: |
          PWD=$(pwd)
          if [[ ! "$(ls -A $PWD/cross/bin)" ]]; then
            chmod +x ./cross-llvm-mingw.sh
            ./cross-llvm-mingw.sh
          fi

      - name: Get current timestamp
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_ENV  

      - name: Packaging toolchain
        run: |
          7z a cross-llvm-mingw-${{ env.date }}-ucrt-x86_64.7z cross/*

      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./release-package.sh
          ./release-package.sh

      - name: Saving llvm cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: cross-llvm-${{ github.run_id }}
