name: cross-gcc-win32 toolchain
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
 
jobs:
  build_cross-gcc-win32-x86_64:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm --needed mingw-w64-gcc
      - uses: actions/checkout@main
      - name: Loading gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-win32-x86_64-ucrt-${{ github.run_id }}
          restore-keys: |
            cross-gcc-win32-x86_64-ucrt-            
      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A cross/bin)" ]]; then
            chmod +x ./cross-gcc-win32.sh
            ./cross-gcc-win32.sh --build-x86_64
          fi        
      - name: Get gcc version
        run: |
           echo "ver=$(cat cross/version.txt)" >> $GITHUB_ENV
      - name: Packaging toolchain
        run: |
          tar -Jcf cross-gcc-win32-${{ env.ver }}-ucrt-x86_64.tar.xz cross
          cp cross-gcc-win32-${{ env.ver }}-ucrt-x86_64.tar.xz cross-gcc-win32-latest-ucrt-x86_64.tar.xz
      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh cross-gcc-win32-latest-ucrt-x86_64.tar.xz
      - name: Release
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        with:
          tag_name: toolchain
          name: toolchain
          files: cross-gcc-win32*.tar.xz
      - name: Saving gcc cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-win32-x86_64-ucrt-${{ github.run_id }}

  build_cross-gcc-win32-x86_64_v3:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm --needed mingw-w64-gcc    
      - uses: actions/checkout@main
      - name: Loading gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-win32-x86_64_v3-ucrt-${{ github.run_id }}
          restore-keys: |
            cross-gcc-win32-x86_64_v3-ucrt-            
      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A cross/bin)" ]]; then
            chmod +x ./cross-gcc-win32.sh
            ./cross-gcc-win32.sh --build-x86_64_v3
          fi        
      - name: Get gcc version
        run: |
           echo "ver=$(cat cross/version.txt)" >> $GITHUB_ENV
      - name: Packaging toolchain
        run: |
          tar -Jcf cross-gcc-win32-${{ env.ver }}-ucrt-x86_64_v3.tar.xz cross
          cp cross-gcc-win32-${{ env.ver }}-ucrt-x86_64_v3.tar.xz cross-gcc-win32-latest-ucrt-x86_64_v3.tar.xz
      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh cross-gcc-win32-latest-ucrt-x86_64_v3.tar.xz
      - name: Release
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        with:
          tag_name: toolchain
          name: toolchain
          files: cross-gcc-win32*.tar.xz
      - name: Saving gcc cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-win32-x86_64_v3-ucrt-${{ github.run_id }}

