name: llvm-mingw
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:          
      - uses: actions/checkout@main
      - name: Loading llvm cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: llvm-mingw-${{ github.run_id }}
          restore-keys: |
            llvm-mingw-
            
      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A cross/bin)" ]]; then
            chmod +x ./llvm-mingw.sh
            ./llvm-mingw.sh
          fi

      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV  

      - name: Packaging toolchain
        run: |
          7z a llvm-mingw-${{ env.date }}-ucrt-x86_64.7z cross/*

      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh

      - name: Saving llvm cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: llvm-mingw-${{ github.run_id }}
