name: Build llvm with pgo
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      llvm_thin_lto:
        description: "Build LLVM with ThinLTO"
        required: false
        default: "false"
        type: boolean
      llvm_full_lto:
        description: "Build LLVM with FullLTO"
        required: false
        default: "false"
        type: boolean
      llvm_ccache:
        description: "Build LLVM with CCACHE"
        required: false
        default: "false"
        type: boolean
      package_lto:
        description: "Build packages with ThinLTO"
        required: false
        default: "false"
        type: boolean        
      package_ccache:
        description: "Build packages with CCACHE"
        required: false
        default: "false"
        type: boolean
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Init variable
        run: |
          if [ ${{ inputs.llvm_thin_lto }} == 'true' ]; then
            echo "LLVM_LTO=--enable-llvm-thin_lto" >> $GITHUB_ENV
          elif [ ${{ inputs.llvm_full_lto }} == 'true' ]; then
            echo "LLVM_LTO=--enable-llvm-full_lto" >> $GITHUB_ENV  
          else
            unset LLVM_LTO
          fi  
          if [ ${{ inputs.llvm_ccache }} == 'true' ]; then
            echo "LLVM_CCACHE=--enable-llvm-ccache" >> $GITHUB_ENV
          else
            unset LLVM_CCACHE
          fi
          if [ ${{ inputs.package_lto }} == 'true' ]; then
            echo "PACKAGE_LTO=--enable-package-lto" >> $GITHUB_ENV
          else
            unset PACKAGE_LTO
          fi           
          if [ ${{ inputs.package_ccache }} == 'true' ]; then
            echo "PACKAGE_CCACHE=--enable-package-ccache" >> $GITHUB_ENV
          else
            unset PACKAGE_CCACHE
          fi 
      
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Load llvm-pgo cache
        uses: actions/cache/restore@main
        id: llvm-pgo
        with:
          path: ${{ github.workspace }}/llvm_root
          key: llvm-pgo-${{ github.run_id }}
          restore-keys: |
            llvm-pgo-

      - name: Setup llvm-clang toolchain with IR Profile Instrumentation
        if: ${{ steps.llvm-pgo.outputs.cache-matched-key == '' }}
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/llvm-clang-ir-latest-ucrt-x86_64.7z
          7z x llvm-clang-ir-latest-ucrt-x86_64.7z
          rm llvm-clang-ir-latest-ucrt-x86_64.7z

      - name: Setup llvm-pgo-latest
        if: ${{ steps.llvm-pgo.outputs.cache-matched-key == '' && inputs.llvm_lto == 'true' }} || ${{ steps.llvm-pgo.outputs.cache-matched-key == '' && inputs.llvm_ccache == 'true' }} || ${{ steps.llvm-pgo.outputs.cache-matched-key == '' && inputs.package_lto == 'true' }} || ${{ steps.llvm-pgo.outputs.cache-matched-key == '' && inputs.package_ccache == 'true' }}
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/llvm-pgo-latest.7z || true
          7z x llvm-pgo-latest.7z || true 
          rm llvm-pgo-latest.7z || true
          rm -rf llvm_root/bin || true
          rm -rf llvm_root/lib || true

      - name: Train pgo with shaderc
        if: ${{ steps.llvm-pgo.outputs.cache-matched-key == '' }}
        run: |
          chmod +x ./train-pgo.sh
          ./train-pgo.sh $PACKAGE_LTO $PACKAGE_CCACHE

      - name: Build llvm with pgo
        if: ${{ steps.llvm-pgo.outputs.cache-matched-key == '' }}
        run: |
          chmod +x ./llvm.sh
          ./llvm.sh --enable-pgo_use $LLVM_LTO $LLVM_CCACHE

      - name: Save llvm-pgo cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/llvm_root
          key: llvm-pgo-${{ github.run_id }}

      - name: Get current timestamp
        if: ${{ steps.llvm-pgo.outputs.cache-matched-key == '' }}
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Package llvm-pgo-latest
        #if: ${{ steps.llvm-pgo.outputs.cache-matched-key == '' }}
        run: 7z a llvm-pgo-latest.7z llvm_root/*
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh


      - name: Package x86_64 toolchain
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/llvm-clang-ir-latest-ucrt-x86_64.7z
          7z x llvm-clang-ir-latest-ucrt-x86_64.7z
          rm llvm-clang-ir-latest-ucrt-x86_64.7z
          ls llvm_root
          rm -rf llvm_root/llvm-thinlto || true
          rm -rf llvm_root/llvm-ccache || true
          rm -rf llvm_root/ccache || true
          rm -rf llvm_root/thinlto || true
          cp -rf llvm_root/* cross
          rm -rf cross/profiles/*
          7z a llvm-clang-pgo-${{ env.date }}-ucrt-x86_64.7z cross/*
          cp llvm-clang-pgo-${{ env.date }}-ucrt-x86_64.7z llvm-clang-pgo-latest-ucrt-x86_64.7z
          rm -rf cross
      - name: Delete
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh llvm-clang-pgo-latest-ucrt-x86_64.7z

      - name: Packaging x86_64_v3 toolchain
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/llvm-clang-ir-latest-ucrt-x86_64_v3.7z
          7z x llvm-clang-ir-latest-ucrt-x86_64_v3.7z
          rm llvm-clang-ir-latest-ucrt-x86_64_v3.7z
          cp -rf llvm_root/* cross
          rm -rf cross/profiles/*
          7z a llvm-clang-pgo-${{ env.date }}-ucrt-x86_64_v3.7z cross/*
          cp llvm-clang-pgo-${{ env.date }}-ucrt-x86_64_v3.7z llvm-clang-pgo-latest-ucrt-x86_64_v3.7z
          rm -rf cross
      - name: Delete
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh llvm-clang-pgo-latest-ucrt-x86_64_v3.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh
      - name: Remove all *.7z packages
        continue-on-error: true
        run: rm *.7z