name: Build cross-gcc-posix-x86_64_v3
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - uses: actions/checkout@main
      - name: Loading gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-posix-x86_64_v3-ucrt-${{ github.run_id }}
          restore-keys: |
            cross-gcc-posix-x86_64_v3-ucrt-
            
      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A cross/bin)" ]]; then
            chmod +x ./cross-gcc-posix-x86_64_v3.sh
            ./cross-gcc-posix-x86_64_v3.sh
          fi

      - name: Get gcc version
        run: |
          echo "ver=$(cat cross/version.txt)" >> $GITHUB_ENV

      - name: Packaging toolchain
        run: |
          7z a cross-gcc-posix-${{ env.ver }}-ucrt-x86_64_v3.7z cross/*
          cp cross-gcc-posix-${{ env.ver }}-ucrt-x86_64_v3.7z cross-gcc-posix-latest-ucrt-x86_64_v3.7z

      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh cross-gcc-posix-latest-ucrt-x86_64_v3.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh

      - name: Saving gcc cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-posix-x86_64_v3-ucrt-${{ github.run_id }}
          
