name: cross-llvm-mingw-toolchain
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build_llvm:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main      
      - name: Loading llvm cache
        uses: actions/cache/restore@main
        id: cross-llvm
        with:
          path: ${{ github.workspace }}/cross
          key: cross-llvm-${{ github.run_id }}
          restore-keys: |
            cross-llvm-
      - name: Load llvm-project source
        uses: actions/cache@main
        id: llvm-source
        with:
          path: ${{ github.workspace }}/source/llvm-project
          key: llvm-source-cache            
      - name: Install host clang toolchain
        if: ${{ steps.cross-llvm.outputs.cache-matched-key == '' }}
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/cross-llvm-clang-pgo-latest-ucrt-x86_64.tar.xz
          tar -xvf cross-llvm-clang-pgo-latest-ucrt-x86_64.tar.xz 2>/dev/null >/dev/null
          rm cross-llvm-clang-pgo-latest-ucrt-x86_64.tar.xz
          mv cross host
      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A cross/bin)" ]]; then
            chmod +x ./cross-llvm.sh
            ./cross-llvm.sh
          fi
      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV  
      - name: Packaging toolchain
        if: ${{ steps.cross-llvm.outputs.cache-matched-key == '' }}
        run: tar -zcvf cross-llvm-latest.tar.xz cross 2>/dev/null >/dev/null
      - name: Saving llvm cache
        if: ${{ steps.cross-llvm.outputs.cache-matched-key == '' }}
        uses: actions/cache/save@main
        with:
          path: ${{ github.workspace }}/cross
          key: cross-llvm-${{ github.run_id }}
      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        if: ${{ steps.cross-llvm.outputs.cache-matched-key == '' }}
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh cross-llvm-latest.tar.xz
      - name: Release
        if: ${{ steps.cross-llvm.outputs.cache-matched-key == '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: toolchain
          name: toolchain
          files: cross-llvm*.tar.xz

  build_llvm-mingw:
    needs: build_llvm
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Load llvm-project source
        uses: actions/cache@main
        id: llvm-source
        with:
          path: ${{ github.workspace }}/source/llvm-project
          key: llvm-source-cache          
      - name: Setup cross-llvm
        run: |
          curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-latest.tar.xz
          tar -xvf cross*.tar.xz 2>/dev/null >/dev/null
          rm cross*.tar.xz            
      - name: Building toolchain
        run: |
          chmod +x ./cross-llvm-mingw.sh
          ./cross-llvm-mingw.sh
      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV  
      - name: Packaging toolchain
        run: |
          tar -zcvf cross-llvm-mingw-${{ env.date }}-ucrt-x86_64.tar.xz cross 2>/dev/null >/dev/null
          cp cross-llvm-mingw-${{ env.date }}-ucrt-x86_64.tar.xz cross-llvm-mingw-latest-ucrt-x86_64.tar.xz
      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh cross-llvm-mingw-latest-ucrt-x86_64.tar.xz
      - name: Release
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        with:
          tag_name: toolchain
          name: toolchain
          files: cross-llvm-mingw*.tar.xz