name: Build cross-llvm-mingw
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - uses: actions/checkout@main          
      - name: Setup cross-llvm
        run: |
          curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-latest.7z
          7z x cross*.7z
          rm cross*.7z
            
      - name: Building toolchain
        run: |
          chmod +x ./cross-llvm-mingw.sh
          ./cross-llvm-mingw.sh

      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV  

      - name: Packaging toolchain
        run: |
          7z a cross-llvm-mingw-${{ env.date }}-ucrt-x86_64.7z cross/*
          cp cross-llvm-mingw-${{ env.date }}-ucrt-x86_64.7z cross-llvm-mingw-latest-ucrt-x86_64.7z

      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh cross-llvm-mingw-latest-ucrt-x86_64.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh
