name: debian-test
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:    
      - name: Install Dependencies
        run: |
          apt-get -y update
          apt-get -y install \
            build-essential \
            yasm \
            nasm \
            git \
            cmake \
            gyp \
            checkinstall \
            bison \
            flex \
            gettext \
            mercurial \
            subversion \
            ninja-build \
            automake \
            pkgconf \
            libtool \
            libtool-bin \
            gcc-multilib \
            g++-multilib \
            libgmp-dev \
            libmpfr-dev \
            libmpc-dev \
            libgcrypt-dev \
            gperf \
            ragel \
            texinfo \
            autopoint \
            re2c \
            asciidoc \
            python3-pip \
            docbook2x \
            unzip \
            p7zip-full \
            curl \
            jq \
            wget
          pip3 install -U --break-system-packages setuptools rst2pdf mako jsonschema meson  
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
          
      - uses: actions/checkout@main
      - name: Loading cross gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-${{ github.run_id }}
          restore-keys: |
            cross-gcc-
            
      - name: Loading target gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/target
          key: target-gcc-${{ github.run_id }}
          restore-keys: |
            taget-gcc-
            
      - name: Building cross gcc
        run: |
          chmod +x ./*.sh
          PWD=$(pwd)
          if [[ ! "$(ls -A $PWD/cross/bin)" ]]; then
            ./update_source.sh
            ./rebuild_cross.sh 64r
          fi
          
      - name: Building target gcc
        run: |
          chmod +x ./*.sh
          rm -rf taget
          PWD=$(pwd)
          if [[ ! "$(ls -A $PWD/taget/bin)" ]]; then
            ./update_source.sh
            ./rebuild_target.sh 64r
          fi

      - name: Packaging toolchain
        run: |
          7z a dgn-cross-gcc.7z cross/*
          7z a dgn-target-gcc.7z target/*

      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./release-package.sh
          ./release-package.sh dgn*.7z

      - name: Saving cross gcc cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: cross-gcc-${{ github.run_id }}
          
      - name: Saving target gcc cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/target
          key: target-gcc-${{ github.run_id }}


 



