name: debian-test
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:    
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install cmake make gcc-c++ bison flex texinfo libtool patch autoconf automake sed diffutils diffstat m4 yasm nasm wget subversion cvs mercurial
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD


 



