name: debian-test
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:    
      - name: Install Dependencies
        run: |
          apt-get -y update
          apt-get -y install \
            build-essential \
            yasm \
            nasm \
            git \
            curl \
            mercurial \
            subversion \
            cvs \
            gcc-multilib \
            bison \
            diffutils \
            flex \
            gperf \
            ragel \
            texinfo \
            patch \
            sed \
            cmake \
            make \
            autopoint \
            gettext \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            pkgconf \
            meson \
            ninja-build \
            python3-distutils \
            python3-jinja2 \
            python3-jsonschema \
            wget \
            p7zip-full \
            unzip
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD


 



