name: Build gcc-mcf-x86_64
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:          
      - uses: actions/checkout@main
      - name: Loading gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: gcc-mcf-x86_64-ucrt-${{ github.run_id }}
          restore-keys: |
            gcc-mcf-x86_64-ucrt-
            
      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A cross/bin)" ]]; then
            chmod +x ./gcc-mcf-x86_64.sh
            ./gcc-mcf-x86_64.sh
          fi

      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV
        
      - name: Get gcc version
        run: |
           echo "ver=$(cat cross/version.txt)" >> $GITHUB_ENV

      - name: Packaging toolchain
        run: |
          7z a gcc-mcf-${{ env.date }}-ucrt-x86_64.7z cross/*
          cp gcc-mcf-${{ env.date }}-ucrt-x86_64.7z gcc-mcf-latest-ucrt-x86_64.7z

      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh gcc-mcf-latest-ucrt-x86_64.7z
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh

      - name: Saving gcc cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: gcc-mcf-x86_64-ucrt-${{ github.run_id }}
