name: ninja
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:    
      - name: Checkout
        uses: actions/checkout@main
          
      - name: Setup Toolchain
        run: |
          curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-gcc-mcf-13.2.0-x64-ucrt.7z
          7z x cross-gcc-mcf*.7z
          rm cross-gcc-mcf*.7z
            
      - name: Building
        run: |
          chmod +x ./ninja.sh
          ./ninja.sh

      - name: Get current time
        run: |
          echo "short_time=$(date "+%Y%m%d")" >> $GITHUB_ENV

      - name: Release
        continue-on-error: true
        uses: softprops/action-gh-release@master
        with:
          tag_name: dev
          name: dev
          files: libjxl.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
