name: rust-toolchain
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:          
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup llvm-clang-pgo toolchain
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/cross-llvm-clang-pgo-latest-ucrt-x86_64.tar.xz
          tar -xvf cross-llvm-clang-pgo-latest-ucrt-x86_64.tar.xz 2>/dev/null >/dev/null
          rm cross-llvm-clang-pgo-latest-ucrt-x86_64.tar.xz

      - name: Building rust toolchain
        run: |
          chmod +x ./rust.sh
          ./rust.sh 

      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Packaging toolchain
        run: |
          7z a rust-${{ env.date }}.7z rust/*
          cp rust-${{ env.date }}.7z rust-latest.7z

      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh rust-latest.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh
