name: shaderc

on:
  workflow_dispatch:
  #schedule:
  #- cron: '30 0 * * MON'
    
jobs:
  shaderc:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autotools git p7zip mingw-w64-x86_64-cmake mingw-w64-x86_64-make     
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@main
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\mingw-gcc
        key: mingw-gcc-w32threads

    - name: Hack Toolchain
      shell: msys2 {0}
      run: |
        pushd /d/mingw-gcc/include/c++/13.1.0
        mv condition_variable orig.condition_variable.h
        mv future orig.future.h
        mv mutex orig.mutex.h
        mv shared_mutex orig.shared_mutex.h
        mv thread orig.thread.h
        popd
        mv mingw-std-threads-hack/* /d/mingw-gcc/include/c++/13.1.0
        curl -OL https://github.com/meganz/mingw-std-threads/archive/refs/heads/master.zip
        7z x master.zip
        mv mingw-std-threads-master/*.h /d/mingw-gcc/include/c++/13.1.0
        
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: MINGW64
        CMAKE: /mingw64/bin/cmake
        MAKE: /mingw64/bin/mingw32-make
      shell: msys2 {0}
      run: |
        cd shaderc-dev; PATH=/usr/bin:/opt/bin:/d/mingw-gcc/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg
    - name: Release
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        ./release-dev.sh shaderc-dev shaderc-dev
