name: Build target-gcc-posix-ucrt-x86_64
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Setup Toolchain
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/gcc-posix-latest-ucrt-x86_64.7z
          7z x gcc-posix*.7z
          rm gcc-posix*.7z
            
      - name: Loading target gcc cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/target
          key: target-gcc-posix-${{ github.run_id }}
          restore-keys: |
            target-gcc-posix-
            
      - name: Building gcc with posix
        run: |
          PWD=$(pwd)
          if [[ ! "$(ls -A target/bin)" ]]; then
            chmod +x ./target-gcc-posix.sh
            ./target-gcc-posix.sh
          fi  

      - name: Get gcc version
        run: |
           echo "ver=$(cat target/version.txt)" >> $GITHUB_ENV
           
      - name: Packaging toolchain
        run: |
          7z a target-gcc-posix-${{ env.ver }}-x64-ucrt.7z target/*

      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./release-package.sh
          ./release-package.sh target-gcc-posix-${{ env.ver }}-x64-ucrt.7z

      - name: Saving target gcc cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/target
          key: target-gcc-posix-${{ github.run_id }}
