name: Build target-llvm-mingw
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:    
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Setup cross-llvm-mingw and target-llvm
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/cross-llvm-mingw-latest-ucrt-x86_64.7z
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/target-llvm-latest-ucrt.7z
          7z x cross*.7z
          7z x target*.7z
          rm *.7z
            
      - name: Building toolchain
        run: |
          chmod +x ./target-llvm-mingw.sh
          ./target-llvm-mingw.sh

      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Packaging toolchain
        run: |
          7z a -r -l target-llvm-mingw-${{ env.date }}-ucrt-x86_64.7z target/*
          cp target-llvm-mingw-${{ env.date }}-ucrt-x86_64.7z target-llvm-mingw-latest-ucrt-x86_64.7z

      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh target-llvm-mingw-latest-ucrt-x86_64.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh