name: target-llvm-mingw(x86_64)
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build_llvm:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - uses: actions/checkout@main      
      - name: Setup cross-llvm-mingw
        run: |
          curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-mingw-latest-ucrt-x86_64.7z
          7z x cross*.7z
          rm cross*.7z
      - name: Loading target-llvm cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/cross
          key: target-llvm-${{ github.run_id }}
          restore-keys: |
            target-llvm-

      - name: Load llvm-project source
        uses: actions/cache@main
        id: llvm-source
        with:
          path: ${{ github.workspace }}/source/llvm-project
          key: llvm-source-cache
            
      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A target/bin)" ]]; then
            chmod +x ./target-llvm.sh
            ./target-llvm.sh
          fi

      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV  

      - name: Packaging toolchain
        run: 7z a target-llvm-latest.7z target/*

      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh target-llvm-latest.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh

      - name: Saving target-llvm cache
        uses: actions/cache/save@main
        if: always()
        with:
          path: ${{ github.workspace }}/cross
          key: target-llvm-${{ github.run_id }}

  build_llvm-mingw:
    needs: build_llvm
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:    
      - name: Checkout
        uses: actions/checkout@main

      - name: Load llvm-project source
        uses: actions/cache@main
        id: llvm-source
        with:
          path: ${{ github.workspace }}/source/llvm-project
          key: llvm-source-cache
                  
      - name: Setup cross-llvm-mingw and target-llvm
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/cross-llvm-mingw-latest-ucrt-x86_64.7z
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/target-llvm-latest.7z
          7z x cross*.7z
          7z x target*.7z
          rm *.7z
            
      - name: Building toolchain
        run: |
          chmod +x ./target-llvm-mingw.sh
          ./target-llvm-mingw.sh

      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Packaging toolchain
        run: |
          7z a -r -l target-llvm-mingw-${{ env.date }}-ucrt-x86_64.7z target/*
          cp target-llvm-mingw-${{ env.date }}-ucrt-x86_64.7z target-llvm-mingw-latest-ucrt-x86_64.7z

      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh target-llvm-mingw-latest-ucrt-x86_64.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh