name: target-llvm-mingw(x86_64)
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build_llvm:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Loading target-llvm cache
        uses: actions/cache/restore@main
        id: target-llvm
        with:
          path: ${{ github.workspace }}/cross
          key: target-llvm-${{ github.run_id }}
          restore-keys: |
            target-llvm-
      - name: Load llvm-project source
        if: ${{ steps.target-llvm.outputs.cache-matched-key == '' }}
        uses: actions/cache@main
        id: llvm-source
        with:
          path: ${{ github.workspace }}/source/llvm-project
          key: llvm-source-cache
      - name: Setup cross-llvm-mingw
        if: ${{ steps.target-llvm.outputs.cache-matched-key == '' }}
        run: |
          curl -OL https://github.com/eko5624/toolchain/releases/download/toolchain/cross-llvm-mingw-latest-ucrt-x86_64.tar.xz
          tar -xvf cross-llvm-mingw*.tar.xz
          rm cross-llvm-mingw*.tar.xz    
      - name: Building toolchain
        if: ${{ steps.target-llvm.outputs.cache-matched-key == '' }}
        run: |
          chmod +x ./target-llvm.sh
          ./target-llvm.sh
      - name: Get current timestamp
        if: ${{ steps.target-llvm.outputs.cache-matched-key == '' }}
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV  
      - name: Packaging toolchain
        if: ${{ steps.target-llvm.outputs.cache-matched-key == '' }}
        run: 7z a target-llvm-latest.7z target/*
      - name: Delete
        if: ${{ steps.target-llvm.outputs.cache-matched-key == '' }}
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh target-llvm-latest.7z
      - name: Release
        if: ${{ steps.target-llvm.outputs.cache-matched-key == '' }}
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh
      - name: Saving target-llvm cache
        if: ${{ steps.target-llvm.outputs.cache-matched-key == '' }}
        uses: actions/cache/save@main
        with:
          path: ${{ github.workspace }}/cross
          key: target-llvm-${{ github.run_id }}

  build_llvm-mingw:
    needs: build_llvm
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:    
      - name: Checkout
        uses: actions/checkout@main
      - name: Load llvm-project source
        uses: actions/cache@main
        id: llvm-source
        with:
          path: ${{ github.workspace }}/source/llvm-project
          key: llvm-source-cache                  
      - name: Setup cross-llvm-mingw and target-llvm
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/cross-llvm-mingw-latest-ucrt-x86_64.tar.xz
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/target-llvm-latest.7z
          tar -xvf cross*.tar.xz 2>/dev/null >/dev/null
          7z x target*.7z
          rm *.tar.xz *.7z      
      - name: Building toolchain
        run: |
          chmod +x ./target-llvm-mingw.sh
          ./target-llvm-mingw.sh
      - name: Get current timestamp
        run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV
      - name: Packaging toolchain
        run: |
          7z a -r target-llvm-mingw-${{ env.date }}-ucrt-x86_64.7z target/*
          cp target-llvm-mingw-${{ env.date }}-ucrt-x86_64.7z target-llvm-mingw-latest-ucrt-x86_64.7z
      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh target-llvm-mingw-latest-ucrt-x86_64.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh