name: target-gcc-win32-ucrt
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:         
      - name: Checkout
        uses: actions/checkout@main        
      - name: Setup Toolchain
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/cross-gcc-win32-latest-ucrt-x86_64.tar.xz
          tar -Jxf cross-gcc-win32*.tar.xz
          rm cross-gcc-win32*.tar.xz          
      - name: Building gcc with thread win32
        run: |
          chmod +x ./target-gcc-win32.sh
          ./target-gcc-win32.sh --build-x86_64 
      - name: Get gcc version
        run: |
          echo "ver=$(cat target/version.txt)" >> $GITHUB_ENV           
      - name: Packaging toolchain
        run: |
          7z a target-gcc-win32-${{ env.ver }}-ucrt-x86_64.7z target/*
          cp target-gcc-win32-${{ env.ver }}-ucrt-x86_64.7z target-gcc-win32-latest-ucrt-x86_64.7z
      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh target-gcc-win32-latest-ucrt-x86_64.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh

  build-x86_64_v3:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/eko5624/archlinux:latest
    steps:         
      - name: Checkout
        uses: actions/checkout@main        
      - name: Setup Toolchain
        run: |
          curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/cross-gcc-win32-latest-ucrt-x86_64.tar.xz
          tar -Jxf cross-gcc-win32*.tar.xz
          rm cross-gcc-win32*.tar.xz           
      - name: Building gcc with thread win32
        run: |
          chmod +x ./target-gcc-win32.sh
          ./target-gcc-win32.sh --build-x86_64_v3 
      - name: Get gcc version
        run: |
          echo "ver=$(cat target/version.txt)" >> $GITHUB_ENV           
      - name: Packaging toolchain
        run: |
          7z a target-gcc-win32-${{ env.ver }}-ucrt-x86_64_v3.7z target/*
          cp target-gcc-win32-${{ env.ver }}-ucrt-x86_64_v3.7z target-gcc-win32-latest-ucrt-x86_64_v3.7z
      - name: Delete
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-delete.sh
          ./package-delete.sh target-gcc-win32-latest-ucrt-x86_64_v3.7z
      - name: Release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }} 
        run: |
          chmod +x ./package-release.sh
          ./package-release.sh
