name: toolchain

on:
  workflow_dispatch:  
  #schedule:
  #- cron: '05 0 * * MON'  
 
jobs:
  build:
    runs-on: windows-2022
    steps: 
    - uses: msys2/setup-msys2@v2
      with:
        location: D:\
        install: base-devel autotools p7zip
    - name: Prepare
      run: git config --global core.autocrlf input
    - uses: actions/checkout@main     
    - uses: actions/cache@main
      id: cache
      with:
        path: D:\m64-1301
        key: mingw-gcc
    
    - name: Setup Toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        curl -OL http://msystem.waw.pl/x265/mingw-gcc1301-20230322.7z
        7z x mingw-gcc*.7z -o/d
        rm -rf /d/m32-1301
        curl -OL https://raw.githubusercontent.com/mingw-w64/mingw-w64/master/mingw-w64-libraries/winpthreads/include/pthread.h
        mv pthread.h /d/m64-1301/x86_64-w64-mingw32/include
        curl -L -o curl-win64-mingw.zip 'https://curl.se/windows/latest.cgi?p=win64-mingw.zip'
        7z e -r curl*.zip -o/d/m64-1301/bin '*.exe' '*.crt'
