#!/bin/bash
DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)
PROG=$DIR/bin/ld.lld
TARGET=x86_64-w64-mingw32
FLAGS="-m i386pep"
FLAGS="$FLAGS -O3 --lto-O3 --lto-CGO3 -s"

if [ "$GC" != "0" ]; then
    LLD_GC="--gc-sections --icf=safe"
fi
if [ "$PDB" == "1" ]; then
    FLAGS="$FLAGS --pdb="
fi

"$PROG" $FLAGS "$@" $LLD_GC $LLD_FLAGS
